app_controllers:
    resource: '../src/Controller/'
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_google_analytics_api:
    resource: "@GoogleAnalyticsApi/Resources/config/routing_dev.yml"